# This is a basic workflow that is manually triggered

name: Automated workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: "11 5 * * *"

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  time: # id of output
  description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'automation.js'


